/* Sample spot data · v2 — monochrome hero gradients.
   No colorful category tints; every hero is a teal→black ramp with
   subtle hue shift per spot for variation without polychrome clash. */
window.SAMPLE_SPOTS = [
  {
    id: "1",
    name: "十八王公廟 · 黑狗分身",
    nameEn: "Eighteen Lords Temple",
    category: "weird-temple",
    status: "active",
    difficulty: "easy",
    distanceKm: 2.4,
    lat: 25.2841,
    lng: 121.5743,
    description: "廟旁永遠守著一隻香火繚繞的黑狗石像。據說會在夜裡跟著路人走一小段，然後悄悄返回。廟方不否認、也不主動提起。",
    legend: "黑狗曾在七〇年代救過一位被海浪捲走的漁民，從此被供奉。",
    hero: "linear-gradient(135deg, #0d2520 0%, #0a1a16 55%, #040c0a 100%)",
  },
  {
    id: "2",
    name: "巨大鳳梨觀景台",
    nameEn: "Giant Pineapple Observatory",
    category: "giant-object",
    status: "active",
    difficulty: "easy",
    distanceKm: 3.8,
    lat: 25.0395,
    lng: 121.5658,
    description: "九〇年代產業文化園區遺跡。七公尺高的水泥鳳梨，內部中空，據說以前可以從鳳梨眼爬上去。現在入口焊死。",
    legend: null,
    hero: "linear-gradient(135deg, #123028 0%, #09201a 55%, #040c0a 100%)",
  },
  {
    id: "3",
    name: "舊北投軍事營區",
    nameEn: "Old Beitou Barracks",
    category: "abandoned",
    status: "uncertain",
    difficulty: "medium",
    distanceKm: 5.1,
    lat: 25.1326,
    lng: 121.5012,
    description: "標語「勤儉建國」還在。水塔倒了。通訊站屋頂有棵長出來的榕樹。入口已無人看守，但路況差。",
    legend: null,
    hero: "linear-gradient(135deg, #0a1a16 0%, #081512 55%, #040c0a 100%)",
  },
  {
    id: "4",
    name: "永和霓虹愛情賓館舊招",
    nameEn: "Yonghe Neon Love Hotel Sign",
    category: "kitsch",
    status: "active",
    difficulty: "easy",
    distanceKm: 1.2,
    lat: 25.0089,
    lng: 121.5152,
    description: "六層樓高的粉紅心形霓虹，仍會在週末閃一半。下方的賓館早已改成便利商店。",
    legend: null,
    hero: "linear-gradient(135deg, #0e2a26 0%, #091f1c 55%, #040c0a 100%)",
  },
  {
    id: "5",
    name: "南機場夜市四樓通道",
    nameEn: "Nanjichang Fourth-Floor Passage",
    category: "marginal-architecture",
    status: "active",
    difficulty: "hard",
    distanceKm: 0.8,
    lat: 25.0302,
    lng: 121.5078,
    description: "四樓的公共走廊違法改成小店鋪。要穿過三戶人家的晾衣竿才能到盡頭那家只在下午兩點開的理髮店。",
    legend: null,
    hero: "linear-gradient(135deg, #0b2420 0%, #081c18 55%, #040c0a 100%)",
  },
  {
    id: "6",
    name: "陽明山鬼夜哭橋",
    nameEn: "Yangmingshan Crying Bridge",
    category: "urban-legend",
    status: "uncertain",
    difficulty: "hard",
    distanceKm: 11.4,
    lat: 25.1555,
    lng: 121.5437,
    description: "當地計程車司機拒載的一段產業道路。雨夜會聽到嬰兒哭聲，但那附近沒有住戶。",
    legend: "1978 年的一場車禍紀錄已從檔案中消失。",
    hero: "linear-gradient(135deg, #0a1f1c 0%, #061814 55%, #020806 100%)",
  },
];
